# Exercise
# Simulate the autoregressive model
# The autoregressive (AR) model is arguably the most widely used time series model. It shares the very familiar interpretation of a simple linear regression, but here each observation is regressed on the previous observation. The AR model also includes the white noise (WN) and random walk (RW) models examined in earlier chapters as special cases.
# 
# The versatile arima.sim() function used in previous chapters can also be used to simulate data from an AR model by setting the model argument equal to list(ar = phi) , in which phi is a slope parameter from the interval (-1, 1). We also need to specify a series length n.
# 
# In this exercise, you will use this command to simulate and plot three different AR models with slope parameters equal to 0.5, 0.9, and -0.75, respectively.
# 
# Instructions
# 100 XP
# Use arima.sim() to simulate 100 observations of an AR model with slope equal to 0.5. To do so, set the model argument equal to list(ar = 0.5) and set the n argument equal to 100. Save this simulated data to x.
# Use a similar call to arima.sim() to simulate 100 observations of an AR model with slope equal to 0.9. Save this data to y.
# Use a third call to arima.sim() to simulate 100 observations of an AR model with slope equal to -0.75 Save this data to z.
# Use plot.ts() with cbind() to plot your three ts objects (x, y, z).

# Simulate an AR model with 0.5 slope
x <- arima.sim(model = list(ar = 0.5), n = 100)

# Simulate an AR model with 0.9 slope
y <- arima.sim(model = list(ar = 0.9), n = 100)

# Simulate an AR model with -0.75 slope
z <- arima.sim(model = list(ar = -0.75), n = 100)

# Plot your simulated data
plot.ts(cbind(x, y, z))


# Exercise
# Estimate the autocorrelation function (ACF) for an autoregression
# What if you need to estimate the autocorrelation function from your data? To do so, you'll need the acf() command, which estimates autocorrelation by exploring lags in your data. By default, this command generates a plot of the relationship between the current observation and lags extending backwards.
# 
# In this exercise, you'll use the acf() command to estimate the autocorrelation function for three new simulated AR series (x, y, and z). These objects have slope parameters 0.5, 0.9, and -0.75, respectively, and are shown in the adjoining figure.
# 
# Instructions
# 100 XP
# Use three calls to acf() to calculate the ACF for x, y, and z, respectively.


# Calculate the ACF for x
acf(x)

# Calculate the ACF for y
acf(y)

# Calculate the ACF for z
acf(z)

# Exercise
# Compare the random walk (RW) and autoregressive (AR) models
# The random walk (RW) model is a special case of the autoregressive (AR) model, in which the slope parameter is equal to 1. Recall from previous chapters that the RW model is not stationary and exhibits very strong persistence. Its sample autocovariance function (ACF) also decays to zero very slowly, meaning past values have a long lasting impact on current values.
# 
# The stationary AR model has a slope parameter between -1 and 1. The AR model exhibits higher persistence when its slope parameter is closer to 1, but the process reverts to its mean fairly quickly. Its sample ACF also decays to zero at a quick (geometric) rate, indicating that values far in the past have little impact on future values of the process.
# 
# In this exercise, you'll explore these qualities by simulating and plotting additional data from an AR model.
# 
# Instructions
# 100 XP
# Use arima.sim() to simulate 200 observations from an AR model with slope 0.9. Save this to x.
# Use ts.plot() to plot x and use acf() to view its sample ACF.
# Now do the same from an AR model with slope 0.98. Save this to y.
# Now do the same from a RW model (z), and compare the time series and sample ACFs generated by these three models.

# Simulate and plot AR model with slope 0.9 
x <- arima.sim(model = list(ar = 0.9), n = 200)
ts.plot(x)
acf(x)

# Simulate and plot AR model with slope 0.98
y <- arima.sim(model = list(ar = 0.98), n = 200) 
ts.plot(y)
acf(y)

# Simulate and plot RW model
z <- arima.sim(model = list(order = c(0, 1, 0)), n = 200)
ts.plot(z)
acf(z)


# Exercise
# Estimate the autoregressive (AR) model
# For a given time series x we can fit the autoregressive (AR) model using the arima() command and setting order equal to c(1, 0, 0). Note for reference that an AR model is an ARIMA(1, 0, 0) model.
# 
# In this exercise, you'll explore additional qualities of the AR model by practicing the arima() command on a simulated time series x as well as the AirPassengers data. This command allows you to identify the estimated slope (ar1), mean (intercept), and innovation variance (sigma^2) of the model.
# 
# Both xand the AirPassengers data are preloaded in your environment. The time series x is shown in the figure on the right.
# 
# Instructions
# 100 XP
# Use arima() to fit the AR model to the series x. Closely examine the output from this command.
# What are the slope (ar1), mean (intercept), and innovation variance (sigma^2) estimates from your previous command? Type them into your R workspace.
# Now, fit the AR model to AirPassengers, saving the results as AR. Use print() to display the fitted model AR.
# Finally, use the commands provided to plot the AirPassengers, calculate the fitted values, and add them to the figure.

x <- c(0.829341215682053,0.458274520250014,0.0527815209813421,0.0630238631886426,-0.736448933670456,-0.568054922711122,-0.0556303934997583,-0.147576956801382,-0.460717856398862,-0.756994382323504,-1.57092782389792,-0.23143324508185,-1.26147738457346,-0.73773591737333,-0.750287534235644,-1.92100782113282,-2.47286806635955,-3.55173256901574,-1.91249276523099,-4.19513657560318,-2.81785994178501,-3.13869992571718,-1.2958459824488,-0.796408283504578,0.830471666329527,-0.2101606448215,-0.313461695673941,0.0586647119401028,1.52705543632923,3.760888467561,3.2545091790514,2.58562423406945,1.21400133984388,1.4902341373066,2.38877470293402,3.5656151892364,3.84286329966219,4.94002290496353,4.68469270318051,3.2465059544223,2.39817012673373,2.10741932905636,1.64408811559573,-0.184780597957703,-1.97232158744387,-0.342839387149195,-2.11707044436836,-2.6927674735831,-2.26053239108151,-2.4555351091037,-2.07961804076237,-2.38469163108972,-1.55285213025286,-2.66500949932868,-3.95567413350084,-2.09065332326746,-1.69197443148885,-1.30314984593376,-2.69825580944564,-2.09330095156518,-2.65812196070345,-2.57208874029773,-1.59851940606478,-1.71253921557674,-1.58704321999119,-1.10272265712547,-1.19439780066796,-1.33265836724201,-0.300117724475413,-0.218453951875102,1.67545977500177,1.19913601685972,1.16528148950191,1.6569937772165,-0.53121627197386,-0.922687057695014,-0.912086641007437,-0.691140858539729,-0.516788907377198,-0.811067373814734,1.78528941125194,3.08153265477488,1.4979069607281,1.81441753464782,2.77403381110657,2.59228331559938,2.43284862940746,0.698626883066833,-0.315400535921524,-1.04872127183717,1.06241883492789,1.69360043658666,2.75453477075819,1.54577888180772,0.908247567913198,2.49094442323365,1.92578525385773,-0.296362435752404,-0.731374782147363,-1.39532217356072)


# Fit the AR model to x
arima(x, order = c(1, 0, 0))

# Copy and paste the slope (ar1) estimate
ar1 <- 0.8575

# Copy and paste the slope mean (intercept) estimate
intercept <- -0.0948

# Copy and paste the innovation variance (sigma^2) estimate
sigma <- 1.022

# Fit the AR model to AirPassengers
AR <- arima(AirPassengers, order = c(1, 0, 0))
print(AR)

# Run the following commands to plot the series and fitted values
ts.plot(AirPassengers)
AR_fitted <- AirPassengers - residuals(AR)
points(AR_fitted, type = "l", col = 2, lty = 2)


# Exercise
# Simple forecasts from an estimated AR model
# Now that you've modeled your data using the arima() command, you are ready to make simple forecasts based on your model. The predict() function can be used to make forecasts from an estimated AR model. In the object generated by your predict() command, the $pred value is the forecast, and the $se value is the standard error for the forecast.
# 
# To make predictions for several periods beyond the last observations, you can use the n.ahead argument in your predict() command. This argument establishes the forecast horizon (h), or the number of periods being forecast. The forecasts are made recursively from 1 to h-steps ahead from the end of the observed time series.
# 
# In this exercise, you'll make simple forecasts using an AR model applied to the Nile data, which records annual observations of the flow of the River Nile from 1871 to 1970.
# 
# Instructions
# 100 XP
# Use arima() to fit an AR model to the Nile time series. Save this as AR_fit.
# Use predict() to make a forecast for flow of the Nile in 1971.
# Use predict_AR along with $pred[1] to obtain the 1-step forecast.
# Use another call to predict() to make forecasts from 1 step ahead to 10 steps ahead (1971 to 1980). To do so, set the n.ahead command equal to 10.
# Run the pre-written code to plot your Nile data plus the forecasts and a 95% prediction interval.

# Fit an AR model to Nile
AR_fit <- arima(Nile, order  = c(1, 0, 0))
print(AR_fit)

# Use predict() to make a 1-step forecast
predict_AR <- predict(AR_fit, n.ahead = 1)

# Obtain the 1-step forecast using $pred[1]
predict_AR$pred[1]

# Use predict to make 1-step through 10-step forecasts
predict(AR_fit, n.ahead = 10)

# Run to plot the Nile series plus the forecast and 95% prediction intervals
ts.plot(Nile, xlim = c(1871, 1980))
AR_forecast <- predict(AR_fit, n.ahead = 10)$pred
AR_forecast_se <- predict(AR_fit, n.ahead = 10)$se
points(AR_forecast, type = "l", col = 2)
points(AR_forecast - 2*AR_forecast_se, type = "l", col = 2, lty = 2)
points(AR_forecast + 2*AR_forecast_se, type = "l", col = 2, lty = 2)



